const ADMIN = sessionStorage.getItem('moriRole') === 'admin';
if (!ADMIN) window.location.href = 'index.html';
const defaults = [{name:'Serein Pendant',type:'necklaces',meta:'Recycled silver / 18”',price:6,image:'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=700&q=85',tag:'New'},{name:'Tide Pool Ring',type:'rings',meta:'Sterling silver',price:4,image:'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=700&q=85'},{name:'Sol Shell Hoops',type:'earrings',meta:'Gold vermeil',price:5,image:'https://images.unsplash.com/photo-1635767798638-3e25273a8236?auto=format&fit=crop&w=700&q=85',tag:'Best seller'},{name:'Moss Cuff',type:'bracelets',meta:'Brass / hand patina',price:7,image:'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?auto=format&fit=crop&w=700&q=85'},{name:'Nami Chain',type:'necklaces',meta:'Gold plated / 16”',price:8,image:'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=700&q=85'},{name:'Pebble Signet',type:'rings',meta:'Sterling silver',price:9,image:'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=700&q=85'},{name:'Pearl Study Studs',type:'earrings',meta:'Freshwater pearl',price:6.1,image:'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=700&q=85',tag:'Limited'},{name:'Luna Threader',type:'earrings',meta:'Recycled silver',price:3,image:'https://images.unsplash.com/photo-1535556116002-6281ff3e9f9c?auto=format&fit=crop&w=700&q=85'}];
let products = JSON.parse(localStorage.getItem('moriProducts') || 'null') || defaults;
let content = JSON.parse(localStorage.getItem('moriContent') || 'null') || {announcement:'Free shipping on orders over $75 ✳ made slowly, worn daily',about:'We believe the best objects become part of you. Chalice Craft is a study in shape, texture and the beautiful pause between too much and just enough.',email:'bychalice.craft@gmail.com',copyright:'© 2026 Chalice Craft',location:'Ho Chi Minh City / Worldwide',legal:'Privacy & terms'};
content.aboutImages = content.aboutImages || ['Image/HRbanner_Chalice%20craft.jpg'];
const $ = id => document.getElementById(id);
const imageField = document.createElement('label'); imageField.textContent = 'Ảnh section About Us'; imageField.innerHTML += '<textarea id="contentAboutImages" placeholder="Mỗi dòng một URL ảnh"></textarea>'; $('contentAbout').closest('label').after(imageField); $('contentAboutImages').value = content.aboutImages.join('\n');
document.getElementById('saveContentButton').addEventListener('click', () => { content.aboutImages = document.getElementById('contentAboutImages').value.split('\n').map(value => value.trim()).filter(Boolean); localStorage.setItem('moriContent', JSON.stringify(content)); });
function renderProducts(){ $('productTable').innerHTML=products.map((p,i)=>`<div class="product-row"><img src="${p.image}" alt="${p.name}"><strong>${p.name}</strong><span class="category">${p.type}</span><span class="row-price">$${Number(p.price).toFixed(2)}</span><div class="row-actions"><button data-edit="${i}">Sửa</button><button class="delete" data-delete="${i}">Xóa</button></div></div>`).join('') || '<p>Chưa có sản phẩm.</p>'; document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openProduct(Number(b.dataset.edit)));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{products.splice(Number(b.dataset.delete),1);saveProducts();renderProducts()})}
function saveProducts(){localStorage.setItem('moriProducts',JSON.stringify(products))}
function openProduct(index=null){$('productModal').classList.add('open');$('productMessage').textContent='';$('productForm').reset();$('productId').value=index===null?'':index;$('productModalTitle').textContent=index===null?'Thêm sản phẩm':'Sửa sản phẩm';if(index!==null){const p=products[index];['Name','Type','Meta','Price','Image','Tag'].forEach(key=>{const field=$(`product${key}`);field.value=p[key.toLowerCase()] ?? ''})}}
$('addProductButton').onclick=()=>openProduct();$('closeProductModal').onclick=()=>$('productModal').classList.remove('open');$('productModal').onclick=e=>{if(e.target.id==='productModal')$('productModal').classList.remove('open')};$('productForm').onsubmit=e=>{e.preventDefault();const value={name:$('productName').value.trim(),type:$('productType').value,meta:$('productMeta').value.trim(),price:Number($('productPrice').value),image:$('productImage').value.trim(),tag:$('productTag').value.trim()};const index=$('productId').value;if(index==='')products.push(value);else products[Number(index)]=value;saveProducts();renderProducts();$('productModal').classList.remove('open')};
['announcement','about','email','copyright','location','legal'].forEach(key=>{ $(`content${key[0].toUpperCase()+key.slice(1)}`).value=content[key] });$('saveContentButton').onclick=()=>{$('contentForm').reportValidity();if(!$('contentForm').checkValidity())return;['announcement','about','email','copyright','location','legal'].forEach(key=>content[key]=$(`content${key[0].toUpperCase()+key.slice(1)}`).value.trim());localStorage.setItem('moriContent',JSON.stringify(content));$('contentMessage').textContent='Đã lưu nội dung website.';setTimeout(()=>$('contentMessage').textContent='',2500)};$('logoutButton').onclick=()=>{sessionStorage.clear();window.location.href='index.html'};renderProducts();
